In [13]:
import pandas as pd

df = pd.read_csv("races.csv")

# print(df.head())
# print(df.isnull().sum())
print(df.dtypes)

# print(df.columns)
# df['driverId']

df.drop(['time'], axis = 1, inplace = True)
df.drop(['url'], axis = 1, inplace = True)
df.drop(['fp1_date'], axis = 1, inplace = True)
df.drop(['fp1_time'], axis = 1, inplace = True)
df.drop(['fp2_date'], axis = 1, inplace = True)
df.drop(['fp2_time'], axis = 1, inplace = True)
df.drop(['fp3_date'], axis = 1, inplace = True)
df.drop(['fp3_time'], axis = 1, inplace = True)
df.drop(['quali_date'], axis = 1, inplace = True)
df.drop(['quali_time'], axis = 1, inplace = True)
df.drop(['sprint_date'], axis = 1, inplace = True)
df.drop(['sprint_time'], axis = 1, inplace = True)


# df.columns =df.columns.str.strip()

df['raceId'] = pd.to_numeric(df['raceId'], errors='coerce')

df = df[(df ['raceId'] >= 1121) & (df ['raceId'] <= 1144)] 

# df['time'] = pd.to_numeric(df['time'], errors='coerce')

# df.loc[(df['raceId'] >= 1121) & (df['raceId'] <= 1144), 'raceId'] = 2024

df = df.sort_values(by='raceId', ascending=True)


print(df.head())


df.to_csv("race_track.csv", index=False)

df.describe()

raceId          int64
year            int64
round           int64
circuitId       int64
name           object
date           object
time           object
url            object
fp1_date       object
fp1_time       object
fp2_date       object
fp2_time       object
fp3_date       object
fp3_time       object
quali_date     object
quali_time     object
sprint_date    object
sprint_time    object
dtype: object
      raceId  year  round  circuitId                      name        date
1101    1121  2024      1          3        Bahrain Grand Prix  2024-03-02
1102    1122  2024      2         77  Saudi Arabian Grand Prix  2024-03-09
1103    1123  2024      3          1     Australian Grand Prix  2024-03-24
1104    1124  2024      4         22       Japanese Grand Prix  2024-04-07
1105    1125  2024      5         17        Chinese Grand Prix  2024-04-21

            raceId    year      round  circuitId
count    24.000000    24.0  24.000000  24.000000
mean   1132.500000  2024.0  12.500000  32.583333
std       7.071068     0.0   7.071068  29.285575
min    1121.000000  2024.0   1.000000   1.000000
25%    1126.750000  2024.0   6.750000  10.500000
50%    1132.500000  2024.0  12.500000  19.500000
75%    1138.250000  2024.0  18.250000  69.250000
max    1144.000000  2024.0  24.000000  80.000000